---

- name: Log in to DockerHub
  community.docker.docker_login:
    state: "present"
    username: '{{ docker_username }}'
    password: '{{ docker_password }}'

- name: Start website docker image
  community.docker.docker_container:
    name: flask_app
    state: started
    image: "{{ patsite_image_name }}"
    restart_policy: "unless-stopped"
    published_ports:
      - 8024:8041
    mounts:
      - source: "/home/ansible/app_files/shared_files"
        target: "/usr/local/lib/python3.12/site-packages/PatrickWilliamsWebsite/app/shared"
        type: bind
        read_only: true

- name: Log out of DockerHub
  community.docker.docker_login:
    state: "absent"
