---

- name: Remove ubuntu user
  ansible.builtin.user:
    name: ubuntu
    remove: true

- name: Copy the contents of the app_files directory
  ansible.builtin.copy:
    src: files/app_files
    dest: /home/ansible/
    owner: ansible
    group: ansible
    force: true
    mode: "0744"

- name: Ensure getNYTdata.py runs everyday at 3:05
  ansible.builtin.cron:
    name: "scrape New York Times"
    minute: "05"
    hour: "3"
    job: "/bin/python3 /home/ansible/app_files/getNYTdata.py"
    user: ansible
    state: present

- name: Gather info on running container
  docker_container_info:
    name: "flask_app"
  register: container_info

- name: Conditionally Run the container_setup playbook
  ansible.builtin.import_tasks: container_setup.yml
  when:  container_info.container.Config.Image  !=  patsite_image_name

- name: Make sure nginx is running
  become: true
  ansible.builtin.systemd:
    name: "nginx"
    state: restarted
    enabled: true
