---

- name: Ensure python3 and pip are installed
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Selenium and Beautiful Soup
  become: true
  ansible.builtin.pip:
    name:
      - selenium
      - beautifulsoup4
    state: present
