"""bees and boxes

Revision ID: c7c7ae47ebf3
Revises: 
Create Date: 2024-12-16 12:54:22.798183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c7ae47ebf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('print_date', sa.DateTime(), nullable=True),
    sa.Column('letters', sa.String(length=7), nullable=False),
    sa.Column('accepted', sa.Text(), nullable=False),
    sa.Column('pangrams', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bees_print_date'), ['print_date'], unique=False)

    op.create_table('boxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('print_date', sa.DateTime(), nullable=True),
    sa.Column('sides', sa.Text(), nullable=False),
    sa.Column('dictionary', sa.Text(), nullable=False),
    sa.Column('one_word', sa.Text(), nullable=True),
    sa.Column('two_word', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boxes_print_date'), ['print_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boxes_print_date'))

    op.drop_table('boxes')
    with op.batch_alter_table('bees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bees_print_date'))

    op.drop_table('bees')
    # ### end Alembic commands ###
